insert into tasks (name, description)
values ('Innovative', 'semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis'),
('optimizing', 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh'),
('heuristic', 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis'),
('hardware', 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta'),
('uniform', 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo'),
('adapter', 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit'),
('Automated', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui'),
('Versatile', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum'),
('bi-directional', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus'),
('application', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet'),
('impactful', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin'),
('discrete', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus'),
('4th generation', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie'),
('Profound', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan'),
('Extended', 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus'),
('value-added', null),
('Triple-buffered', 'congue etiam justo etiam pretium iaculis justo in hac habitasse'),
('Persistent', 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec'),
('zero defect', 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla'),
('Devolved', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis'),
('multimedia', 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum'),
('systematic', 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec'),
('extranet', null),
('object-oriented', 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra'),
('4th generation', null),
('attitude', null),
('static', 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit'),
('human-resource', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla'),
('project', 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit'),
('standardization', null);
