DROP TABLE IF EXISTS TASKS;
DROP TABLE IF EXISTS TASK_LISTS;
DROP TABLE IF EXISTS BOARDS;

create table BOARDS (
	ID					INT NOT NULL AUTO_INCREMENT,
	NAME 		VARCHAR(50),

	PRIMARY KEY (ID)
);

create table TASK_LISTS (
	ID					INT NOT NULL AUTO_INCREMENT,
	BOARD_ID			INT NOT NULL,
	NAME 		VARCHAR(50),

	PRIMARY KEY (ID),
	FOREIGN KEY (BOARD_ID) REFERENCES BOARDS(ID)
);

create table TASKS (
	ID					INT NOT NULL AUTO_INCREMENT,
	TASK_LIST_ID		INT,
	NAME 		VARCHAR(50),
	DESCRIPTION		   TEXT,

	PRIMARY KEY (ID),
	FOREIGN KEY (TASK_LIST_ID) REFERENCES TASK_LISTS(ID)
);
